version: "3.9"

services:
  stt-backend:
    build: .
    container_name: stt-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu] # Solo se vuoi usare GPU
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia # Necessario per GPU
