version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.cpu  # o Dockerfile.gpu
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
